### ISSUE TITLE
Sommige integratie tests van de brmo-loader falen op Windows

### ISSUE THREAD

**Issue by mprins** [B3Partners/brmo#1028]
### Probleem
Sommige integratie tests van de brmo-loader falen op Windows als zo'n test een bericht moet transformeren en de tests met java 11 en Maven draaien 
het gaat om:

Failures:
- `BRKLocatiebeschrijvingIntegrationTest#testLocatieBeschrijving`
- `BrkToStagingToRsgbIntegrationTest#testBrkXMLToStaging`
- `GH789GroteWaardeIDIntegrationTest#testTransformBerichten`
- `Mantis10315IntegrationTest#testTransformBerichten`
- `Mantis10547IntegrationTest#testAll`
- `Mantis11180IntegrationTest#testTransformBerichten`
- `Mantis6098IntegrationTest#testAll`
- `Mantis6098IntegrationTest#testStand`
- `Mantis6098IntegrationTest#testStandDelete`
- `Mantis6098IntegrationTest#testStandDeleteMutatie`
- `Mantis6098IntegrationTest#testStandMutatie`
- `Mantis6166IntegrationTest#testAll`
- `Mantis6166IntegrationTest#testStand`
- `Mantis6166IntegrationTest#testStandDelete`
- `Mantis6166IntegrationTest#testStandDeleteMutatie`
- `Mantis6166IntegrationTest#testStandMutatie`
- `Mantis6380IntegrationTest#testTransformBerichten`
- `Mantis6380IntegrationTest#testTransformStand`
- `Mantis6380IntegrationTest#testTransformStandDaarnaMutatieBerichten`
- `VerminderenStukdelenIntegrationTest#testMinderStukdelenInMutatie`
- `ZakRechtArchiefIntegrationTest#transformeerberichten`
- `BagBerichtIntegrationTest#loadAll`

ontdekt tijdens maken van  #1025 (dus vooralsnog ronden we die af met java 8...)

de kern van het probleem blijkt uit de melding:
```
BRMO-LOADER-TEST: ERROR 17:40:32 (n.b.b.l.RsgbProxy#updateBerichtException:422) - Mutatieverwerking en foutief bericht, dus stoppen!
java.nio.file.InvalidPathException: Illegal char <:> at index 21: org\geotools\gml3\jar:file:\C:\Users\mark\.m2\repository\org\geotools\xsd\gt-xsd-gml3\24.2\gt-xsd-gml3-24.2.jar!\org\geotools\gml3\gml.xsd
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
```

Er gaat dus iets mis met de constructie van het pad naar de xsd. De tests draaien wel goed vanuit de IDE / Intellij.

### stacktrace
<details><summary>maven log:</summary>

```

[INFO] Running nl.b3p.brmo.loader.entity.BagBerichtIntegrationTest
BRMO-LOADER-TEST:  INFO 17:40:30 (n.b.AbstractDatabaseIntegrationTest#startTest:103) - ==== Start test methode: loadInStaging()
BRMO-LOADER-TEST:  INFO 17:40:31 (n.b.AbstractDatabaseIntegrationTest#endTest:111) - ==== Einde test methode: loadInStaging()
BRMO-LOADER-TEST:  INFO 17:40:31 (n.b.AbstractDatabaseIntegrationTest#startTest:103) - ==== Start test methode: loadAll()
BRMO-LOADER-TEST: ERROR 17:40:32 (n.b.b.l.RsgbProxy#updateBerichtException:422) - Mutatieverwerking en foutief bericht, dus stoppen!
java.nio.file.InvalidPathException: Illegal char <:> at index 21: org\geotools\gml3\jar:file:\C:\Users\mark\.m2\repository\org\geotools\xsd\gt-xsd-gml3\24.2\gt-xsd-gml3-24.2.jar!\org\geotools\gml3\gml.xsd
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
        at java.base/jdk.internal.module.Resources.toSafeFilePath(Resources.java:143)
        at java.base/jdk.internal.module.Resources.toFilePath(Resources.java:97)
        at java.base/jdk.internal.module.ModulePatcher$ExplodedResourceFinder.find(ModulePatcher.java:505)
        at java.base/jdk.internal.module.ModulePatcher$PatchedModuleReader.findResourceInPatch(ModulePatcher.java:301)
        at java.base/jdk.internal.module.ModulePatcher$PatchedModuleReader.find(ModulePatcher.java:357)
        at java.base/jdk.internal.loader.BuiltinClassLoader$2.run(BuiltinClassLoader.java:407)
        at java.base/jdk.internal.loader.BuiltinClassLoader$2.run(BuiltinClassLoader.java:402)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findMiscResource(BuiltinClassLoader.java:401)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findResource(BuiltinClassLoader.java:288)
        at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:1401)
        at java.base/java.lang.Class.getResource(Class.java:2740)
        at org.geotools.xsd.SchemaLocationResolver.resolveLocationToResource(SchemaLocationResolver.java:111)
        at org.geotools.xsd.SchemaLocationResolver.canHandle(SchemaLocationResolver.java:102)
        at org.geotools.xsd.SchemaLocationResolver.resolveSchemaLocation(SchemaLocationResolver.java:151)
        at org.geotools.xsd.impl.ParserHandler.startElement(ParserHandler.java:399)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:510)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(XMLNSDocumentScannerImpl.java:613)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3063)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:836)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:324)
        at org.geotools.xsd.Parser.parse(Parser.java:184)
        at org.geotools.xsd.Parser.parse(Parser.java:139)
        at brmo.loader/nl.b3p.brmo.loader.util.DataComfortXMLReader.readDataXML(DataComfortXMLReader.java:185)
        at brmo.loader/nl.b3p.brmo.loader.RsgbProxy.transformToTableData(RsgbProxy.java:362)
        at brmo.loader/nl.b3p.brmo.loader.RsgbProxy.handle(RsgbProxy.java:485)
        at brmo.loader/nl.b3p.brmo.loader.StagingProxy$1.handle(StagingProxy.java:410)
        at brmo.loader/nl.b3p.brmo.loader.StagingProxy$1.handle(StagingProxy.java:377)
        at org.apache.commons.dbutils.QueryRunner.query(QueryRunner.java:388)
        at org.apache.commons.dbutils.QueryRunner.query(QueryRunner.java:266)
        at brmo.loader/nl.b3p.brmo.loader.StagingProxy.handleBerichtenByJob(StagingProxy.java:377)
        at brmo.loader/nl.b3p.brmo.loader.RsgbProxy.run(RsgbProxy.java:289)
        at java.base/java.lang.Thread.run(Thread.java:834)
BRMO-LOADER-TEST: ERROR 17:40:32 (n.b.b.l.RsgbProxy#handle:560) - Fout bij verwerking bericht met id 41402969931, melding: null
BRMO-LOADER-TEST: ERROR 17:40:32 (n.b.b.l.RsgbProxy#updateBerichtException:422) - Mutatieverwerking en foutief bericht, dus stoppen!
java.lang.NullPointerException
        at brmo.loader/nl.b3p.brmo.loader.StagingProxy.updateBerichtProcessing(StagingProxy.java:689)
        at brmo.loader/nl.b3p.brmo.loader.RsgbProxy.updateProcessingResult(RsgbProxy.java:336)
        at brmo.loader/nl.b3p.brmo.loader.RsgbProxy.transformToTableData(RsgbProxy.java:372)
        at brmo.loader/nl.b3p.brmo.loader.RsgbProxy.handle(RsgbProxy.java:485)
        at brmo.loader/nl.b3p.brmo.loader.StagingProxy$1.handle(StagingProxy.java:410)
        at brmo.loader/nl.b3p.brmo.loader.StagingProxy$1.handle(StagingProxy.java:377)
        at org.apache.commons.dbutils.QueryRunner.query(QueryRunner.java:388)
        at org.apache.commons.dbutils.QueryRunner.query(QueryRunner.java:266)
        at brmo.loader/nl.b3p.brmo.loader.StagingProxy.handleBerichtenByJob(StagingProxy.java:377)
        at brmo.loader/nl.b3p.brmo.loader.RsgbProxy.run(RsgbProxy.java:289)
        at java.base/java.lang.Thread.run(Thread.java:834)
BRMO-LOADER-TEST: ERROR 17:40:32 (n.b.b.l.RsgbProxy#run:293) - Fout tijdens verwerken berichten
java.lang.NullPointerException
        at brmo.loader/nl.b3p.brmo.loader.StagingProxy.updateBerichtProcessing(StagingProxy.java:689)
        at brmo.loader/nl.b3p.brmo.loader.RsgbProxy.updateProcessingResult(RsgbProxy.java:336)
        at brmo.loader/nl.b3p.brmo.loader.RsgbProxy.handle(RsgbProxy.java:581)
        at brmo.loader/nl.b3p.brmo.loader.StagingProxy$1.handle(StagingProxy.java:410)
        at brmo.loader/nl.b3p.brmo.loader.StagingProxy$1.handle(StagingProxy.java:377)
        at org.apache.commons.dbutils.QueryRunner.query(QueryRunner.java:388)
        at org.apache.commons.dbutils.QueryRunner.query(QueryRunner.java:266)
        at brmo.loader/nl.b3p.brmo.loader.StagingProxy.handleBerichtenByJob(StagingProxy.java:377)
        at brmo.loader/nl.b3p.brmo.loader.RsgbProxy.run(RsgbProxy.java:289)
        at java.base/java.lang.Thread.run(Thread.java:834)
BRMO-LOADER-TEST:  INFO 17:40:32 (n.b.AbstractDatabaseIntegrationTest#endTest:111) - ==== Einde test methode: loadAll()
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.926 s <<< FAILURE! - in nl.b3p.brmo.loader.entity.BagBerichtIntegrationTest
```

</details>

**Comment by mprins** [comment]
op linux:
```
└─ $ ▶ diff java8.deps.txt java11.deps.txt
20d19
< [INFO] |  |     \- xml-apis:xml-apis:jar:1.4.01:compile
< [INFO] |  \- org.hsqldb:hsqldb:jar:2.5.1:compile
---
> [INFO] |  +- org.hsqldb:hsqldb:jar:2.5.1:compile
> [INFO] |  +- jakarta.activation:jakarta.activation-api:jar:1.2.2:compile
> [INFO] |  \- org.glassfish.jaxb:jaxb-runtime:jar:2.3.3:compile
> [INFO] |     +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.3:compile
> [INFO] |     +- org.glassfish.jaxb:txw2:jar:2.3.3:compile
> [INFO] |     +- com.sun.istack:istack-commons-runtime:jar:3.0.11:compile
> [INFO] |     \- com.sun.activation:jakarta.activation:jar:1.2.2:runtime


```

**Comment by mprins** [comment]
bij de laatste:
```
[INFO] Running nl.b3p.brmo.loader.entity.BagBerichtIntegrationTest
BRMO-LOADER-TEST:  INFO 17:40:30 (n.b.AbstractDatabaseIntegrationTest#startTest:103) - ==== Start test methode: loadInStaging()
BRMO-LOADER-TEST:  INFO 17:40:31 (n.b.AbstractDatabaseIntegrationTest#endTest:111) - ==== Einde test methode: loadInStaging()
BRMO-LOADER-TEST:  INFO 17:40:31 (n.b.AbstractDatabaseIntegrationTest#startTest:103) - ==== Start test methode: loadAll()
BRMO-LOADER-TEST: ERROR 17:40:32 (n.b.b.l.RsgbProxy#updateBerichtException:422) - Mutatieverwerking en foutief bericht, dus stoppen!
java.nio.file.InvalidPathException: Illegal char <:> at index 21: org\geotools\gml3\jar:file:\C:\Users\mark\.m2\repository\org\geotools\xsd\gt-xsd-gml3\24.2\gt-xsd-gml3-24.2.jar!\org\geotools\gml3\gml.xsd
        at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
        at java.base/jdk.internal.module.Resources.toSafeFilePath(Resources.java:143)
        at java.base/jdk.internal.module.Resources.toFilePath(Resources.java:97)
        at java.base/jdk.internal.module.ModulePatcher$ExplodedResourceFinder.find(ModulePatcher.java:505)
        at java.base/jdk.internal.module.ModulePatcher$PatchedModuleReader.findResourceInPatch(ModulePatcher.java:301)
        at java.base/jdk.internal.module.ModulePatcher$PatchedModuleReader.find(ModulePatcher.java:357)
        at java.base/jdk.internal.loader.BuiltinClassLoader$2.run(BuiltinClassLoader.java:407)
        at java.base/jdk.internal.loader.BuiltinClassLoader$2.run(BuiltinClassLoader.java:402)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findMiscResource(BuiltinClassLoader.java:401)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findResource(BuiltinClassLoader.java:288)
        at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:1401)
        at java.base/java.lang.Class.getResource(Class.java:2740)
        at org.geotools.xsd.SchemaLocationResolver.resolveLocationToResource(SchemaLocationResolver.java:111)
        at org.geotools.xsd.SchemaLocationResolver.canHandle(SchemaLocationResolver.java:102)
        at org.geotools.xsd.SchemaLocationResolver.resolveSchemaLocation(SchemaLocationResolver.java:151)
        at org.geotools.xsd.impl.ParserHandler.startElement(ParserHandler.java:399)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:510)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl$NSContentDriver.scanRootElementHook(XMLNSDocumentScannerImpl.java:613)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3063)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:836)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:324)
        at org.geotools.xsd.Parser.parse(Parser.java:184)
        at org.geotools.xsd.Parser.parse(Parser.java:139)
        at brmo.loader/nl.b3p.brmo.loader.util.DataComfortXMLReader.readDataXML(DataComfortXMLReader.java:185)
        at brmo.loader/nl.b3p.brmo.loader.RsgbProxy.transformToTableData(RsgbProxy.java:362)
        at brmo.loader/nl.b3p.brmo.loader.RsgbProxy.handle(RsgbProxy.java:485)
        at brmo.loader/nl.b3p.brmo.loader.StagingProxy$1.handle(StagingProxy.java:410)
        at brmo.loader/nl.b3p.brmo.loader.StagingProxy$1.handle(StagingProxy.java:377)
        at org.apache.commons.dbutils.QueryRunner.query(QueryRunner.java:388)
        at org.apache.commons.dbutils.QueryRunner.query(QueryRunner.java:266)
        at brmo.loader/nl.b3p.brmo.loader.StagingProxy.handleBerichtenByJob(StagingProxy.java:377)
        at brmo.loader/nl.b3p.brmo.loader.RsgbProxy.run(RsgbProxy.java:289)
        at java.base/java.lang.Thread.run(Thread.java:834)
BRMO-LOADER-TEST: ERROR 17:40:32 (n.b.b.l.RsgbProxy#handle:560) - Fout bij verwerking bericht met id 41402969931, melding: null
BRMO-LOADER-TEST: ERROR 17:40:32 (n.b.b.l.RsgbProxy#updateBerichtException:422) - Mutatieverwerking en foutief bericht, dus stoppen!
java.lang.NullPointerException
        at brmo.loader/nl.b3p.brmo.loader.StagingProxy.updateBerichtProcessing(StagingProxy.java:689)
        at brmo.loader/nl.b3p.brmo.loader.RsgbProxy.updateProcessingResult(RsgbProxy.java:336)
        at brmo.loader/nl.b3p.brmo.loader.RsgbProxy.transformToTableData(RsgbProxy.java:372)
        at brmo.loader/nl.b3p.brmo.loader.RsgbProxy.handle(RsgbProxy.java:485)
        at brmo.loader/nl.b3p.brmo.loader.StagingProxy$1.handle(StagingProxy.java:410)
        at brmo.loader/nl.b3p.brmo.loader.StagingProxy$1.handle(StagingProxy.java:377)
        at org.apache.commons.dbutils.QueryRunner.query(QueryRunner.java:388)
        at org.apache.commons.dbutils.QueryRunner.query(QueryRunner.java:266)
        at brmo.loader/nl.b3p.brmo.loader.StagingProxy.handleBerichtenByJob(StagingProxy.java:377)
        at brmo.loader/nl.b3p.brmo.loader.RsgbProxy.run(RsgbProxy.java:289)
        at java.base/java.lang.Thread.run(Thread.java:834)
BRMO-LOADER-TEST: ERROR 17:40:32 (n.b.b.l.RsgbProxy#run:293) - Fout tijdens verwerken berichten
java.lang.NullPointerException
        at brmo.loader/nl.b3p.brmo.loader.StagingProxy.updateBerichtProcessing(StagingProxy.java:689)
        at brmo.loader/nl.b3p.brmo.loader.RsgbProxy.updateProcessingResult(RsgbProxy.java:336)
        at brmo.loader/nl.b3p.brmo.loader.RsgbProxy.handle(RsgbProxy.java:581)
        at brmo.loader/nl.b3p.brmo.loader.StagingProxy$1.handle(StagingProxy.java:410)
        at brmo.loader/nl.b3p.brmo.loader.StagingProxy$1.handle(StagingProxy.java:377)
        at org.apache.commons.dbutils.QueryRunner.query(QueryRunner.java:388)
        at org.apache.commons.dbutils.QueryRunner.query(QueryRunner.java:266)
        at brmo.loader/nl.b3p.brmo.loader.StagingProxy.handleBerichtenByJob(StagingProxy.java:377)
        at brmo.loader/nl.b3p.brmo.loader.RsgbProxy.run(RsgbProxy.java:289)
        at java.base/java.lang.Thread.run(Thread.java:834)
BRMO-LOADER-TEST:  INFO 17:40:32 (n.b.AbstractDatabaseIntegrationTest#endTest:111) - ==== Einde test methode: loadAll()
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.926 s <<< FAILURE! - in nl.b3p.brmo.loader.entity.BagBerichtIntegrationTest
```
