### ISSUE TITLE
Doorstuur proces crashed na X (veel) berichten met java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by mprins** [B3Partners/brmo#114]
logfile:
```
2016-01-12 10:16:05 INFO  nl.b3p.brmo.service.scanner.GDS2OphalenProces#doorsturenBericht - Bericht NL.KAD.OnroerendeZaak:2530242470000 op 12-01-2016 10:16:05 doorgestuurd naar http://levering-Z/service/brk
2016-01-12 10:16:06 INFO  nl.b3p.brmo.service.scanner.GDS2OphalenProces#doorsturenBericht - Bericht NL.KAD.OnroerendeZaak:3150203570000 op 12-01-2016 10:16:06 doorgestuurd naar http://levering-Z/service/brk
2016-01-12 10:16:06 INFO  nl.b3p.brmo.service.scanner.GDS2OphalenProces#doorsturenBericht - Bericht NL.KAD.OnroerendeZaak:3200036070000 op 12-01-2016 10:16:06 doorgestuurd naar http://levering-Z/service/brk
2016-01-12 10:16:06 INFO  nl.b3p.brmo.service.scanner.GDS2OphalenProces#doorsturenBericht - Bericht NL.KAD.OnroerendeZaak:2960135870000 op 12-01-2016 10:16:06 doorgestuurd naar http://levering-Z/service/brk
2016-01-12 10:16:23 WARN  net.sourceforge.stripes.exception.DefaultExceptionHandler#warn - Unhandled exception caught by the Stripes default exception handler.
net.sourceforge.stripes.exception.StripesServletException: ActionBean execution threw an exception.
	at net.sourceforge.stripes.controller.DispatcherServlet.service(DispatcherServlet.java:183)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:260)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:610)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:313)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at org.postgresql.core.Utils.encodeUTF8(Utils.java:64)
	at org.postgresql.core.v3.SimpleParameterList.getV3Length(SimpleParameterList.java:307)
	at org.postgresql.core.v3.QueryExecutorImpl.sendBind(QueryExecutorImpl.java:1277)
	at org.postgresql.core.v3.QueryExecutorImpl.sendOneQuery(QueryExecutorImpl.java:1581)
	at org.postgresql.core.v3.QueryExecutorImpl.sendQuery(QueryExecutorImpl.java:1096)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:396)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2900)
	at org.apache.tomcat.dbcp.dbcp.DelegatingStatement.executeBatch(DelegatingStatement.java:297)
	at org.apache.tomcat.dbcp.dbcp.DelegatingStatement.executeBatch(DelegatingStatement.java:297)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:70)
	at org.hibernate.jdbc.BatchingBatcher.addToBatch(BatchingBatcher.java:56)
	at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:2591)
	at org.hibernate.persister.entity.AbstractEntityPersister.updateOrInsert(AbstractEntityPersister.java:2495)
	at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:2822)
	at org.hibernate.action.EntityUpdateAction.execute(EntityUpdateAction.java:113)
	at org.hibernate.engine.ActionQueue.execute(ActionQueue.java:273)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:265)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:185)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:321)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:51)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1216)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:383)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:133)
	at org.hibernate.ejb.TransactionImpl.commit(TransactionImpl.java:76)
	at nl.b3p.brmo.service.scanner.BerichtDoorsturenProces.execute(BerichtDoorsturenProces.java:127)
	at nl.b3p.brmo.service.stripes.BerichtDoorsturenUitvoerActionBean.execute(BerichtDoorsturenUitvoerActionBean.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.sourceforge.stripes.controller.DispatcherHelper$6.intercept(DispatcherHelper.java:456)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:158)
2016-01-12 10:16:23 ERROR org.stripesstuff.plugin.waitpage.Context#error - 
java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:8081/brmo-service/__WPI_THREAD__.wait?proces=5&__WPI__=1419c4fd&_sourcePage=9xitlwe4qV4%3D
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at org.stripesstuff.plugin.waitpage.Context.run(Context.java:110)
	at java.lang.Thread.run(Unknown Source)
2016-01-12 10:16:24 WARN  net.sourceforge.stripes.exception.DefaultExceptionHandler#warn - Unhandled exception caught by the Stripes default exception handler.
net.sourceforge.stripes.exception.StripesServletException: ActionBean execution threw an exception.
	at net.sourceforge.stripes.controller.DispatcherServlet.service(DispatcherServlet.java:183)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:260)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:610)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:315)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at org.postgresql.core.Utils.encodeUTF8(Utils.java:64)
	at org.postgresql.core.v3.SimpleParameterList.getV3Length(SimpleParameterList.java:307)
	at org.postgresql.core.v3.QueryExecutorImpl.sendBind(QueryExecutorImpl.java:1277)
	at org.postgresql.core.v3.QueryExecutorImpl.sendOneQuery(QueryExecutorImpl.java:1581)
	at org.postgresql.core.v3.QueryExecutorImpl.sendQuery(QueryExecutorImpl.java:1096)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:396)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2900)
	at org.apache.tomcat.dbcp.dbcp.DelegatingStatement.executeBatch(DelegatingStatement.java:297)
	at org.apache.tomcat.dbcp.dbcp.DelegatingStatement.executeBatch(DelegatingStatement.java:297)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:70)
	at org.hibernate.jdbc.BatchingBatcher.addToBatch(BatchingBatcher.java:56)
	at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:2591)
	at org.hibernate.persister.entity.AbstractEntityPersister.updateOrInsert(AbstractEntityPersister.java:2495)
	at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:2822)
	at org.hibernate.action.EntityUpdateAction.execute(EntityUpdateAction.java:113)
	at org.hibernate.engine.ActionQueue.execute(ActionQueue.java:273)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:265)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:185)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:321)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:51)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1216)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:383)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:133)
	at org.hibernate.ejb.TransactionImpl.commit(TransactionImpl.java:76)
	at nl.b3p.brmo.service.scanner.BerichtDoorsturenProces.execute(BerichtDoorsturenProces.java:127)
	at nl.b3p.brmo.service.stripes.BerichtDoorsturenUitvoerActionBean.execute(BerichtDoorsturenUitvoerActionBean.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.sourceforge.stripes.controller.DispatcherHelper$6.intercept(DispatcherHelper.java:456)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:158)
```

**Comment by mprins** [comment]
Heapdump analyse; het lijkt erop dat veel meer dat de `commitPageSize` aan berichten in het geheugen blijft zitten

![image](https://cloud.githubusercontent.com/assets/1165786/12354183/7dc81a72-bb94-11e5-9de2-4c704f161264.png)

**Comment by mprins** [comment]
Lokaal kunnen reproduceren met een set van ~28000 brk berichten; bij een Commit page size van 100 treedt er een heap space fout op na 5800 berichten, bij een Commit page size van 10 loopt het doorstuur proces succesvol door. de ooit, arbitrair gekozen waarde van 1000 is waarschijnlijk te hoog..

zie ook #4babd24cc1c531df08afb7ff8f5099a056b386d9

**Comment by mprins** [comment]
dit is op te lossen met configuratie van het automatich proces
