### ISSUE TITLE
ligplaats transformeren mislukt

### ISSUE THREAD

**Issue by mprins** [B3Partners/brmo#116]
met de melding als:
```
2016-01-25 14:32:09 INFO  nl.b3p.brmo.loader.pipeline.ProcessDbXmlPipeline#run - started, waiting for work
2016-01-25 14:32:21 ERROR nl.b3p.brmo.loader.RsgbProxy#handle - Fout bij verwerking bericht met id 817274
java.lang.IllegalArgumentException: Column not found: fk_nn_lh_lpl_sc_identif in table standplaats_nummeraand
	at nl.b3p.brmo.loader.RsgbProxy.getValueAsObject(RsgbProxy.java:1475)
	at nl.b3p.brmo.loader.RsgbProxy.createInsertSql(RsgbProxy.java:866)
	at nl.b3p.brmo.loader.RsgbProxy.parseNewData(RsgbProxy.java:583)
	at nl.b3p.brmo.loader.RsgbProxy.handle(RsgbProxy.java:432)
	at nl.b3p.brmo.loader.pipeline.ProcessDbXmlPipeline.work(ProcessDbXmlPipeline.java:17)
	at nl.b3p.brmo.loader.pipeline.BerichtPipelineThread.run(BerichtPipelineThread.java:83)
```
mogelijk wordt de verkeerde sql gegenereerd met bag-mutate-to-rsgb-xml.xsl de kolomnaam  `fk_nn_lh_lpl_sc_identif` lijkt naar een ligplaats te verwijzen; vermoedelijk moet het veld `fk_nn_lh_spl_sc_identif` heten

**Comment by mprins** [comment]
nagekomen bericht:
> De foutmelding zit niet in Standplaatsen zoals ik eerder zei maar in Ligplaatsen, de verwarring komt waarschijnlijk door de foutmelding. Hieruit blijkt dus dat er wel ligplaats data goed is ingelezen.

Zie bijlage voor de resultaten van deze 2 query’s:

1.  SELECT id, status, opmerking FROM [brmo_staging].[dbo].[bericht] where object_ref like 'LIG%' and status = 'RSGB_NOK';

[Ligplaatsen_PZH_NOK.csv.txt](https://github.com/B3Partners/brmo/files/106236/Ligplaatsen_PZH_NOK.csv.txt)

2.  SELECT id, status FROM [brmo_staging].[dbo].[bericht] where object_ref like 'LIG%';
[Ligplaatsen_PZH.csv.txt](https://github.com/B3Partners/brmo/files/106238/Ligplaatsen_PZH.csv.txt)

**Comment by mprins** [comment]
gesloten in f786c8932ab3cecf675683119065b7e44248f438
