### ISSUE TITLE
incorrecte sql syntax voor query met paginering

### ISSUE THREAD

**Issue by mprins** [B3Partners/brmo#130]
Tijdens transformeren van een selectie treed de volgende fout op:

```
2016-02-10 17:24:33 ERROR nl.b3p.brmo.loader.RsgbProxy#run - Fout tijdens verwerken berichten

java.sql.SQLException: Incorrect syntax near 'OFFSET'. Query: select * from bericht where job_id = ? and status = 'RSGB_WAITING' OFFSET 0 ROWS FETCH NEXT 250 ROWS ONLY Parameters: [1455121422996]
            at org.apache.commons.dbutils.AbstractQueryRunner.rethrow(AbstractQueryRunner.java:392)
            at org.apache.commons.dbutils.QueryRunner.query(QueryRunner.java:351)
            at org.apache.commons.dbutils.QueryRunner.query(QueryRunner.java:212)
            at nl.b3p.brmo.loader.StagingProxy.handleBerichtenByJob(StagingProxy.java:281)
            at nl.b3p.brmo.loader.RsgbProxy.run(RsgbProxy.java:265)
            at java.lang.Thread.run(Unknown Source)
2016-02-10 17:24:34 INFO nl.b3p.brmo.loader.pipeline.ProcessDbXmlPipeline#run - aborting!
```

zie: http://mantis.b3p.nl/view.php?id=5654

**Comment by mprins** [comment]
de query met paginering met gebruik van OFFSET... FETCH moet voorzien zijn van een ORDER BY clause; dat is hier niet het geval.

Zie https://msdn.microsoft.com/en-us/library/gg699618.aspx?f=255&MSPPError=-2147217396
