### ISSUE TITLE
GDS2 crash tijdens doorsturen van grote verzameling berichten

### ISSUE THREAD

**Issue by mprins** [B3Partners/brmo#167]
Het lijkt erop dat het doorsturen van grote verzamelingen berichten tijdens/na ophalen van berichten een crash kan veroorzaken. (de gewone doorstuur job werkt wel OK)

~~wacht op stack trace / log file~~ beide traces wijzen niet op een fout tijdens doorsturen

**Comment by mprins** [comment]
Waarschijnlijk een out-of-memory probleem omdat de lijst met berichten te groot wordt of de hibernate cache overloopt (dit laatste niet waarschijnlijk omdat na ieder bericht een commit/flush naar de database wordt uitgevoerd).

[1] is op te lossen door ipv. de volledige berichten in een lijst bij te houden alleen de berichtid vast te houden;
zie: https://github.com/B3Partners/brmo/blob/master/brmo-service/src/main/java/nl/b3p/brmo/service/scanner/GDS2OphalenProces.java#L678-L693

**Comment by mprins** [comment]
```
 

2016-06-02 14:55:11 INFO  nl.b3p.brmo.service.scanner.GDS2OphalenProces#addLog - Downloaden https://service30.kadaster.nl/gds2/download/private/9462bf88-7306-4f6d-b0c3-9d57564a27ce

2016-06-02 14:55:13 INFO  nl.b3p.brmo.service.scanner.GDS2OphalenProces#addLog - Downloaden https://service30.kadaster.nl/gds2/download/private/896529d0-5c37-4bff-9e77-75ca47b25d1c

2016-06-02 14:55:15 INFO  nl.b3p.brmo.service.scanner.GDS2OphalenProces#addLog - Downloaden https://service30.kadaster.nl/gds2/download/private/5a6be657-6c2e-4329-9839-a8a1472b7862

2016-06-02 14:55:20 WARN  net.sourceforge.stripes.exception.DefaultExceptionHandler#warn - Unhandled exception caught by the Stripes default exception handler.

net.sourceforge.stripes.exception.StripesServletException: ActionBean execution threw an exception.

        at net.sourceforge.stripes.controller.DispatcherServlet.service(DispatcherServlet.java:183)

        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)

        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)

        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)

        at net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:260)

        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)

        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)

        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)

        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)

        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)

        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)

        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:610)

        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)

        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98)

        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)

        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)

        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)

        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)

        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)

        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:313)

        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

        at java.lang.Thread.run(Thread.java:745)

Caused by: java.lang.OutOfMemoryError: Java heap space

        at nl.b3p.brmo.service.stripes.GDS2OphalenUitvoerActionBean.addLog(GDS2OphalenUitvoerActionBean.java:100)

        at nl.b3p.brmo.service.scanner.GDS2OphalenProces.laadAfgifte(GDS2OphalenProces.java:424)

        at nl.b3p.brmo.service.scanner.GDS2OphalenProces.verwerkAfgiftes(GDS2OphalenProces.java:650)

        at nl.b3p.brmo.service.scanner.GDS2OphalenProces.execute(GDS2OphalenProces.java:380)

        at nl.b3p.brmo.service.stripes.GDS2OphalenUitvoerActionBean.execute(GDS2OphalenUitvoerActionBean.java:118)

        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

        at java.lang.reflect.Method.invoke(Method.java:498)

        at net.sourceforge.stripes.controller.DispatcherHelper$6.intercept(DispatcherHelper.java:456)

        at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:158)

        at net.sourceforge.stripes.controller.BeforeAfterMethodInterceptor.intercept(BeforeAfterMethodInterceptor.java:113)

        at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)

        at org.stripesstuff.plugin.waitpage.WaitPageInterceptor.intercept(WaitPageInterceptor.java:125)

        at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)

        at net.sourceforge.stripes.controller.ExecutionContext.wrap(ExecutionContext.java:74)

        at net.sourceforge.stripes.controller.DispatcherHelper.invokeEventHandler(DispatcherHelper.java:454)

        at net.sourceforge.stripes.controller.DispatcherServlet.invokeEventHandler(DispatcherServlet.java:278)

        at net.sourceforge.stripes.controller.DispatcherServlet.service(DispatcherServlet.java:160)

        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)

        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)

        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)

        at net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:260)

        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)

        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)

        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)

        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)

        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)

        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)

        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:610)

        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)

2016-06-02 14:55:20 ERROR org.stripesstuff.plugin.waitpage.Context#error -

java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:8081/brmo-service/__WPI_THREAD__.wait?proces=1&__WPI__=6b8ac095&_sourcePage=fwAgyiz0m68%3D

        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1840)

        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)

        at org.stripesstuff.plugin.waitpage.Context.run(Context.java:110)

        at java.lang.Thread.run(Thread.java:745)
```

**Comment by mprins** [comment]
Hierbij resultaten van Zeeland:
```
 
2016-06-02 16:23:07 INFO  nl.b3p.brmo.service.scanner.GDS2OphalenProces#addLog - Downloaden https://service30.kadaster.nl/gds2/download/private/bbb39017-f3c6-4033-949d-454fb55b7bda
2016-06-02 16:23:08 INFO  nl.b3p.brmo.service.scanner.GDS2OphalenProces#addLog - Downloaden https://service30.kadaster.nl/gds2/download/private/5fc663ef-f69c-4cec-9428-433515bc5970
2016-06-02 16:23:10 INFO  nl.b3p.brmo.service.scanner.GDS2OphalenProces#addLog - Downloaden https://service30.kadaster.nl/gds2/download/private/2a7ae09b-7aeb-41f1-b6eb-dbf38559e691
2016-06-02 16:23:12 INFO  nl.b3p.brmo.service.scanner.GDS2OphalenProces#addLog - Downloaden https://service30.kadaster.nl/gds2/download/private/d005b325-0319-4e8b-a9ee-7d217e53a274
2016-06-02 16:23:13 INFO  nl.b3p.brmo.service.scanner.GDS2OphalenProces#addLog - Downloaden https://service30.kadaster.nl/gds2/download/private/6aec3f24-1db4-4d4e-9ac0-da9400d52416
2016-06-02 16:23:15 INFO  nl.b3p.brmo.service.scanner.GDS2OphalenProces#addLog - Downloaden https://service30.kadaster.nl/gds2/download/private/d5a82a7e-a601-40b4-ad70-aadb9d54ab3a
2016-06-02 16:23:18 INFO  nl.b3p.brmo.service.scanner.GDS2OphalenProces#addLog - Downloaden https://service30.kadaster.nl/gds2/download/private/66aa5c97-0633-4f1d-83bf-78e97aefe00c
2016-06-02 16:23:23 ERROR org.hibernate.AssertionFailure#<init> - an assertion failure occured (this may indicate a bug in Hibernate, but is more likely due to unsafe use of the session)
org.hibernate.AssertionFailure: null id in nl.b3p.brmo.persistence.staging.Bericht entry (don't flush the Session after an exception occurs)
        at org.hibernate.event.def.DefaultFlushEntityEventListener.checkId(DefaultFlushEntityEventListener.java:82)
        at org.hibernate.event.def.DefaultFlushEntityEventListener.getValues(DefaultFlushEntityEventListener.java:190)
        at org.hibernate.event.def.DefaultFlushEntityEventListener.onFlushEntity(DefaultFlushEntityEventListener.java:147)
        at org.hibernate.event.def.AbstractFlushingEventListener.flushEntities(AbstractFlushingEventListener.java:219)
        at org.hibernate.event.def.AbstractFlushingEventListener.flushEverythingToExecutions(AbstractFlushingEventListener.java:99)
        at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:50)
        at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1216)
        at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:383)
        at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:133)
        at org.hibernate.ejb.TransactionImpl.commit(TransactionImpl.java:76)
        at nl.b3p.brmo.service.scanner.GDS2OphalenProces.execute(GDS2OphalenProces.java:400)
        at nl.b3p.brmo.service.scanner.GDS2OphalenProces.execute(GDS2OphalenProces.java:107)
        at nl.b3p.brmo.service.jobs.AutomatischProcesJob.execute(AutomatischProcesJob.java:40)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2016-06-02 16:23:23 ERROR org.hibernate.AssertionFailure#<init> - an assertion failure occured (this may indicate a bug in Hibernate, but is more likely due to unsafe use of the session)
org.hibernate.AssertionFailure: null id in nl.b3p.brmo.persistence.staging.Bericht entry (don't flush the Session after an exception occurs)
        at org.hibernate.event.def.DefaultFlushEntityEventListener.checkId(DefaultFlushEntityEventListener.java:82)
        at org.hibernate.event.def.DefaultFlushEntityEventListener.getValues(DefaultFlushEntityEventListener.java:190)
        at org.hibernate.event.def.DefaultFlushEntityEventListener.onFlushEntity(DefaultFlushEntityEventListener.java:147)
        at org.hibernate.event.def.AbstractFlushingEventListener.flushEntities(AbstractFlushingEventListener.java:219)
        at org.hibernate.event.def.AbstractFlushingEventListener.flushEverythingToExecutions(AbstractFlushingEventListener.java:99)
        at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:50)
        at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1216)
        at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:383)
        at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:133)
        at org.hibernate.ejb.TransactionImpl.commit(TransactionImpl.java:76)
        at nl.b3p.brmo.service.jobs.AutomatischProcesJob.execute(AutomatischProcesJob.java:62)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2016-06-02 16:23:23 ERROR org.quartz.core.JobRunShell#run - Job DEFAULT.proces_3 threw an unhandled Exception:
javax.persistence.RollbackException: Error while committing the transaction
        at org.hibernate.ejb.TransactionImpl.commit(TransactionImpl.java:93)
        at nl.b3p.brmo.service.jobs.AutomatischProcesJob.execute(AutomatischProcesJob.java:62)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.hibernate.AssertionFailure: null id in nl.b3p.brmo.persistence.staging.Bericht entry (don't flush the Session after an exception occurs)
        at org.hibernate.event.def.DefaultFlushEntityEventListener.checkId(DefaultFlushEntityEventListener.java:82)
        at org.hibernate.event.def.DefaultFlushEntityEventListener.getValues(DefaultFlushEntityEventListener.java:190)
        at org.hibernate.event.def.DefaultFlushEntityEventListener.onFlushEntity(DefaultFlushEntityEventListener.java:147)
        at org.hibernate.event.def.AbstractFlushingEventListener.flushEntities(AbstractFlushingEventListener.java:219)
        at org.hibernate.event.def.AbstractFlushingEventListener.flushEverythingToExecutions(AbstractFlushingEventListener.java:99)
        at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:50)
        at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1216)
        at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:383)
        at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:133)
        at org.hibernate.ejb.TransactionImpl.commit(TransactionImpl.java:76)
        ... 3 more
2016-06-02 16:23:23 ERROR org.quartz.core.ErrorLogger#schedulerError - Job (DEFAULT.proces_3 threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: javax.persistence.RollbackException: Error while committing the transaction]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: javax.persistence.RollbackException: Error while committing the transaction
        at org.hibernate.ejb.TransactionImpl.commit(TransactionImpl.java:93)
        at nl.b3p.brmo.service.jobs.AutomatischProcesJob.execute(AutomatischProcesJob.java:62)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        ... 1 more
Caused by: org.hibernate.AssertionFailure: null id in nl.b3p.brmo.persistence.staging.Bericht entry (don't flush the Session after an exception occurs)
        at org.hibernate.event.def.DefaultFlushEntityEventListener.checkId(DefaultFlushEntityEventListener.java:82)
        at org.hibernate.event.def.DefaultFlushEntityEventListener.getValues(DefaultFlushEntityEventListener.java:190)
        at org.hibernate.event.def.DefaultFlushEntityEventListener.onFlushEntity(DefaultFlushEntityEventListener.java:147)
        at org.hibernate.event.def.AbstractFlushingEventListener.flushEntities(AbstractFlushingEventListener.java:219)
        at org.hibernate.event.def.AbstractFlushingEventListener.flushEverythingToExecutions(AbstractFlushingEventListener.java:99)
        at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:50)
        at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1216)
        at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:383)
        at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:133)
        at org.hibernate.ejb.TransactionImpl.commit(TransactionImpl.java:76)
        ... 3 more
```

**Comment by onnlinetool** [comment]
Downloaden Downloaden Downloaden Downloaden Downloaden Downloaden Downloaden 

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi
