### ISSUE TITLE
SAXParseException tijdens verwerken bgtlight met kruinlijn geometrie

### ISSUE THREAD

**Issue by mprins** [B3Partners/brmo#186]
log:
``` 
2016-08-02 11:46:22 DEBUG nl.b3p.brmo.loader.gml.BGTGMLLightLoader#processZipFile - Lezen GML bestand: bgt_ondersteunendwegdeel.gml uit zip file: /mnt/7AEE8BD2EE8B84DB/bgt-zips/drenthe/52670_0-06-06-2016.zip
2016-08-02 11:46:23 WARN  org.geotools.xml#log - cvc-complex-type.2.4.d: Invalid content was found starting with element 'imgeo-s:kruinlijn'. No child element is expected at this point.
2016-08-02 11:46:23 ERROR nl.b3p.brmo.loader.gml.BGTGMLLightLoader#processZipFile - Er is een parse fout opgetreden tijdens verwerken van bgt_ondersteunendwegdeel.gml uit /mnt/7AEE8BD2EE8B84DB/bgt-zips/drenthe/52670_0-06-06-2016.zip
org.xml.sax.SAXParseException; lineNumber: 2; columnNumber: 456228; cvc-complex-type.2.4.d: Invalid content was found starting with element 'imgeo-s:kruinlijn'. No child element is expected at this point.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(XMLSchemaValidator.java:452)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.reportSchemaError(XMLSchemaValidator.java:3230)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:1794)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:740)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:380)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2781)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:504)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
	at org.geotools.xml.Parser.parse(Parser.java:249)
	at org.geotools.xml.Parser.parse(Parser.java:179)
	at nl.b3p.brmo.loader.gml.BGTGMLLightLoader.storeFeatureCollection(BGTGMLLightLoader.java:301)
	at nl.b3p.brmo.loader.gml.BGTGMLLightLoader.processZipFile(BGTGMLLightLoader.java:186)
	at nl.b3p.brmo.loader.util.BGTLightRsgbTransformer.transform(BGTLightRsgbTransformer.java:54)
	at nl.b3p.brmo.loader.util.BGTLightRsgbTransformer.run(BGTLightRsgbTransformer.java:103)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mprins** [comment]
[bgt_ondersteunendwegdeel.gml.zip](https://github.com/B3Partners/brmo/files/396394/bgt_ondersteunendwegdeel.gml.zip)
