### ISSUE TITLE
STRAATNAAM past soms niet in veld in GEM_OPENB_RMTE

### ISSUE THREAD

**Issue by mprins** [B3Partners/brmo#240]
In het geval er multibyte chars in een "straatnaam" zitten is de naam soms groter dan er in het varchar2(24) veld past (afhankelijk van hoe Oracle is geconfigureerd).

Dat komt omdat Oracle voor de lengte van de default karakterset (ascii) uitgaat die in bytes overeenkomt met de lengte van karakters; als er multi-byte karakters (bijv. met diakrieten) in een string zitten kan het voorkomen dat de lengte te groot wordt voor het veld.

<details>
<summary>fout log</summary>
```
2016-10-18 22:18:26 ERROR nl.b3p.brmo.loader.RsgbProxy#handle - Fout bij verwerking bericht met id 18151019

java.sql.SQLException: ORA-12899: waarde te groot voor kolom "BRMO_RSGB"."GEM_OPENB_RMTE"."STRAATNAAM" (huidige waarde: 25, maximumwaarde: 24)
                at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
                at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
                at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1059)
                at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:522)
                at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:257)
                at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:587)
                at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:225)
                at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:53)
                at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)
                at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1150)
                at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:4798)
                at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:4875)
                at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)
                at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:97)
                at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:97)
                at nl.b3p.brmo.loader.RsgbProxy.createInsertSql(RsgbProxy.java:1066)
                at nl.b3p.brmo.loader.RsgbProxy.parseNewData(RsgbProxy.java:683)
                at nl.b3p.brmo.loader.RsgbProxy.handle(RsgbProxy.java:521)
                at nl.b3p.brmo.loader.pipeline.ProcessDbXmlPipeline.work(ProcessDbXmlPipeline.java:17)
                at nl.b3p.brmo.loader.pipeline.BerichtPipelineThread.run(BerichtPipelineThread.java:87)
```

</details>

**Comment by mprins** [comment]
het schijnt dat dit ook (nog) heeft te maken met hoe de database is geïnstalleerd (met welke default character set; zou dat een unicode character set zijn dan zou het probleem niet optreden)

De opties op dit moment:

1. omzetten van de velden naar char lengte dus VARCHAR2(24) wordt dan VARCHAR2(24 CHAR)
2. omzetten van de VARCHAR2 naar NVARCHAR2
3. vergroten van het veld/de velden (maar hoe groot moeten ze dan worden?... )
4. ...

zie ook: [Length Semantics for Character Datatypes](https://docs.oracle.com/cd/B28359_01/server.111/b28318/datatype.htm#CDEFDGFE)

**Comment by mprins** [comment]
> ... ik wist niet dat het wel goed gaat met VARCHAR2(24 CHAR).
> Ik vind dat de beste optie, wij hadden ooit NVARCHAR2, maar daar hadden we ook op één of andere manier last van (ik weet niet meer precies hoe of wat).

> NLS_LENGTH_SEMANTICS staat bij ons op BYTE.

> MB

**Comment by mprins** [comment]
De installatie handleiding is aangepast om het euvel te voorkomen, daarnaast maken we een utility script om het probleem te verhelpen op bestaande installaties door de kolom met `VARCHAR2(24 CHAR)` te (her)definieren
