### ISSUE TITLE
bgtlight verwerken als update mislukt soms met topologie fout

### ISSUE THREAD

**Issue by mprins** [B3Partners/brmo#314]
We zouden eens moeten kijken of we de self-union in [BGTGMLLightLoader](https://github.com/B3Partners/brmo/blob/v1.4.4/bgt-gml-loader/src/main/java/nl/b3p/brmo/loader/gml/BGTGMLLightLoader.java#L211) kunnen vervangen door een robuustere optie; 

Onderzoek destijds heeft uitgewezen dat dit de snelste optie was met acceptabel resultaat; maar mogelijk kan er een snap-to-self met clean gedaan worden.

zie ook [mantis 6322](http://mantis.b3p.nl/view.php?id=6322)

```
Laadprocessen bgtlight (4150) transformeren

Gestart op: 2017-03-14 17:11:21, 2 uur geleden. 
Update: 2017-03-14 18:28:24
Totaal: 99
Verwerkt: 30
Status: Transformatie afgerond.

Proces afgebroken vanwege een exception:

com.vividsolutions.jts.geom.TopologyException: found non-noded intersection between LINESTRING ( 240046.37162016786 554910.601380438, 240046.37272164322 554910.6017120297 ) and LINESTRING ( 240046.37272164295 554910.6017120295, 240046.37162016702 554910.6013804377 ) [ (240046.3720181931, 554910.6015002608, NaN) ]

        at com.vividsolutions.jts.noding.FastNodingValidator.checkValid(FastNodingValidator.java:130)

        at com.vividsolutions.jts.geomgraph.EdgeNodingValidator.checkValid(EdgeNodingValidator.java:94)

        at com.vividsolutions.jts.geomgraph.EdgeNodingValidator.checkValid(EdgeNodingValidator.java:59)

        at com.vividsolutions.jts.operation.overlay.OverlayOp.computeOverlay(OverlayOp.java:170)

        at com.vividsolutions.jts.operation.overlay.OverlayOp.getResultGeometry(OverlayOp.java:127)

        at com.vividsolutions.jts.operation.overlay.OverlayOp.overlayOp(OverlayOp.java:66)

        at com.vividsolutions.jts.operation.overlay.snap.SnapIfNeededOverlayOp.getResultGeometry(SnapIfNeededOverlayOp.java:96)

        at com.vividsolutions.jts.operation.overlay.snap.SnapIfNeededOverlayOp.overlayOp(SnapIfNeededOverlayOp.java:58)

        at com.vividsolutions.jts.geom.Geometry.union(Geometry.java:1395)

        at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.unionActual(CascadedPolygonUnion.java:384)

        at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.unionOptimized(CascadedPolygonUnion.java:307)

        at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.unionSafe(CascadedPolygonUnion.java:288)

        at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.binaryUnion(CascadedPolygonUnion.java:219)

        at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.binaryUnion(CascadedPolygonUnion.java:225)

        at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.binaryUnion(CascadedPolygonUnion.java:200)

        at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.unionTree(CascadedPolygonUnion.java:146)

        at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.reduceToGeometries(CascadedPolygonUnion.java:259)

        at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.unionTree(CascadedPolygonUnion.java:144)

        at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.reduceToGeometries(CascadedPolygonUnion.java:259)

        at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.unionTree(CascadedPolygonUnion.java:144)

        at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.reduceToGeometries(CascadedPolygonUnion.java:259)

        at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.unionTree(CascadedPolygonUnion.java:144)

        at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.reduceToGeometries(CascadedPolygonUnion.java:259)

        at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.unionTree(CascadedPolygonUnion.java:144)

        at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.union(CascadedPolygonUnion.java:134)

        at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.union(CascadedPolygonUnion.java:80)

        at com.vividsolutions.jts.operation.union.UnaryUnionOp.union(UnaryUnionOp.java:176)

        at com.vividsolutions.jts.operation.union.UnaryUnionOp.union(UnaryUnionOp.java:95)

        at com.vividsolutions.jts.geom.Geometry.union(Geometry.java:1484)

        at nl.b3p.brmo.loader.gml.BGTGMLLightLoader.processZipFile(BGTGMLLightLoader.java:211)

        at nl.b3p.brmo.loader.util.BGTLightRsgbTransformer.transform(BGTLightRsgbTransformer.java:53)

        at nl.b3p.brmo.loader.util.BGTLightRsgbTransformer.run(BGTLightRsgbTransformer.java:102)

        at java.lang.Thread.run(Unknown Source)

Log:

Initialiseren... di mrt 14 17:11:21 CET 2017

Het laadproces transformatie proces met ID 4150 is gestart op di mrt 14 17:11:21 CET 2017.

Laadproces transformatie proces met ID 4150 is succesvol afgerond op di mrt 14 18:56:40 CET 2017.

 

```

**Comment by matthijsln** [comment]
Voorstel feature te verwijderen, altijd TRUNCATE (of DELETE ALL) en volledige stand inladen.

Bij nieuwe PDOK download service zitten mutaties dus is feature toch niet meer nodig.
