### ISSUE TITLE
Transaction not active fout bij starten proces door Quartz

### ISSUE THREAD

**Issue by matthijsln** [B3Partners/brmo#38]
```
2015-03-16 17:36:22 ERROR nl.b3p.brmo.service.jobs.AutomatischProcesJob - Fout tijdens starten of uitvoeren van automatische proces met id:
java.lang.IllegalStateException: Transaction not active
        at org.hibernate.ejb.TransactionImpl.commit(TransactionImpl.java:69)
        at nl.b3p.brmo.service.jobs.AutomatischProcesJob.execute(AutomatischProcesJob.java:38)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
```

**Comment by mprins** [comment]
Ik vermoed dat hier een niet bestaand (verwijderd) proces gestart werd aangezien de id niet is vermeld in de log/foutmelding (wat normaal gezien wel het geval moet zijn)

Dat mag na 0b6881e en f3ffda6 niet meer voorkomen.
