### ISSUE TITLE
Verwerken Top10NL mislukt vanwege ongekend type "PlanTopografie"

### ISSUE THREAD

**Issue by mprins** [B3Partners/brmo#384]
<details><summary>server log / stacktrace:</summary>

```
2017-11-17 10:04:04 INFO  nl.b3p.brmo.service.scanner.LaadprocesTransformatieUitvoeren#execute - Het laadproces transformatie proces met ID 2 is gestart op Fri Nov 17 10:04:04 CET 2017.
2017-11-17 10:04:05 INFO  nl.b3p.topnl.Processor#importIntoDb - Importing file file:/mnt/tera1/klant-data/xxx/Top10NL/TOP10NL_07W.gml, type: top10nl

2017-11-17 10:10:14 ERROR nl.b3p.brmo.loader.util.TopNLRsgbTransformer#run - Fout tijdens verwerken TOPNL laadprocessen
java.lang.IllegalArgumentException: Type not recognized: class nl.b3p.topnl.top10nl.PlanTopografieType
	at nl.b3p.topnl.converters.Top10NLConverter.convertObject(Top10NLConverter.java:131)
	at nl.b3p.topnl.converters.Top10NLConverter.convertFeatureCollection(Top10NLConverter.java:91)
	at nl.b3p.topnl.converters.Top10NLConverter.convert(Top10NLConverter.java:75)
	at nl.b3p.topnl.Processor.convert(Processor.java:143)
	at nl.b3p.topnl.Processor.importIntoDb(Processor.java:86)
	at nl.b3p.brmo.loader.util.TopNLRsgbTransformer.transform(TopNLRsgbTransformer.java:53)
	at nl.b3p.brmo.loader.util.TopNLRsgbTransformer.run(TopNLRsgbTransformer.java:89)
	at java.lang.Thread.run(Thread.java:748)
```

</details>

download file: [TOP10NL_07W.zip](http://geodata.nationaalgeoregister.nl/top10nlv2/extract/kaartbladen/TOP10NL_07W.zip?formaat=gml)

**Comment by mprins** [comment]
de postgresql definitie mist ook een gemetrie kolom (of kolommen, kennelijk kan het een punt of een lijn zijn):
```
-- Table: top10nl.plantopografie

-- DROP TABLE top10nl.plantopografie;

CREATE TABLE top10nl.plantopografie
(
  topnltype text,
  id serial NOT NULL,
  identificatie text,
  brontype text,
  bronactualiteit timestamp without time zone,
  bronbeschrijving text,
  bronnauwkeurigheid double precision,
  objectbegintijd timestamp without time zone,
  objecteindtijd timestamp without time zone,
  visualisatiecode integer,
  typeplantopografie text,
  naam text,
  CONSTRAINT plantopografie_pkey PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE top10nl.plantopografie
  OWNER TO rsgb;
```
