### ISSUE TITLE
Sommige elementen(alle?) van top250 willen niet transformeren

### ISSUE THREAD

**Issue by mprins** [B3Partners/brmo#394]
### Probleem
Kennelijk is de GML niet geldig... de logfile staat vol met de melding `Error parsing javax.xml.bind.UnmarshalException`

het gaat om de download van 27/11 van `http://geodata.nationaalgeoregister.nl/top250nl/extract/kaartbladtotaal/top250nl.zip?formaat=gml`

### Versie

Versie: | 1.5.2-SNAPSHOT-13a582d 
-- | --
Build time: | 27.11.2017 @ 12:00:02 CET
Build by: | Mark Prins
Git details
Git branch: | bug/top10nlfixes
Git remote url: | git@github.com:B3Partners/brmo.git
Git commit abbrev id: | 13a582d
Git commit full id: | 13a582de7f317553a7cb9e66ccb09536c342201f
Git commit time: | 27.11.2017 @ 09:26:11 CET

zie ook #392 

### Server log
<details><summary>server log:</summary>

```

2017-11-27 14:24:52 ERROR nl.b3p.topnl.Processor#importIntoDb - Error parsing
javax.xml.bind.UnmarshalException
 - with linked exception:
[com.sun.istack.SAXParseException2; lineNumber: 2484711; columnNumber: 3; unexpected element (
uri:"http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.1", local:"FeatureMember"). 
Expected elements are <{http://www.opengis.net/gml/3.2}AbstractCurve>,
<{http://www.opengis.net/gml/3.2}AbstractFeature>,
<{http://www.opengis.net/gml/3.2}AbstractGML>,
<{http://www.opengis.net/gml/3.2}AbstractGeometricAggregate>,
<{http://www.opengis.net/gml/3.2}AbstractGeometricPrimitive>,
<{http://www.opengis.net/gml/3.2}AbstractGeometry>,
<{http://www.opengis.net/gml/3.2}AbstractMetaData>,
<{http://www.opengis.net/gml/3.2}AbstractObject>,
<{http://www.opengis.net/gml/3.2}AbstractSurface>,
<{http://register.geostandaarden.nl/gmlapplicatieschema/brt-algemeen/1.2.0}BRTLijnOfPunt>,
<{http://register.geostandaarden.nl/gmlapplicatieschema/brt-algemeen/1.2.0}BRTVlakLijnOfPunt>,
<{http://register.geostandaarden.nl/gmlapplicatieschema/brt-algemeen/1.2.0}BRTVlakMultivlakOfPunt>,
<{http://register.geostandaarden.nl/gmlapplicatieschema/brt-algemeen/1.2.0}BRTVlakOfLijn>,
<{http://register.geostandaarden.nl/gmlapplicatieschema/brt-algemeen/1.2.0}BRTVlakOfMultivlak>,
<{http://www.opengis.net/gml/3.2}Envelope>,
<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}FeatureCollectionT250NL>,
<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}FeatureMember>,
<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}FunctioneelGebied>,
<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}Gebouw>,
<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}GeografischGebied>,
<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}Hoogte>,
<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}Inrichtingselement>,
<{http://www.opengis.net/gml/3.2}LocationKeyWord>,
<{http://www.opengis.net/gml/3.2}LocationString>,
<{http://www.opengis.net/gml/3.2}MultiSurface>,
<{http://register.geostandaarden.nl/gmlapplicatieschema/brt-algemeen/1.2.0}NEN3610ID>,
<{http://www.opengis.net/gml/3.2}Null>,
<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}Plaats>,
<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}PlanTopografie>,
<{http://www.opengis.net/gml/3.2}Point>,
<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}RegistratiefGebied>,
<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}Relief>,
<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}Spoorbaandeel>,
<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}Terrein>,
<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}Waterdeel>,
<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}Wegdeel>,
<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}_Top250nlObject>,
<{http://www.opengis.net/gml/3.2}boundedBy>,
<{http://www.opengis.net/gml/3.2}coordinates>,
<{http://www.opengis.net/gml/3.2}description>,
<{http://www.opengis.net/gml/3.2}descriptionReference>,
<{http://www.opengis.net/gml/3.2}identifier>,
<{http://www.opengis.net/gml/3.2}location>,
<{http://www.opengis.net/gml/3.2}metaDataProperty>,
<{http://www.opengis.net/gml/3.2}name>,
<{http://www.opengis.net/gml/3.2}pos>,
<{http://www.opengis.net/gml/3.2}surfaceMember>,
<{http://www.opengis.net/gml/3.2}surfaceMembers>]
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.handleStreamException(UnmarshallerImpl.java:483)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:417)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:386)
	at nl.b3p.topnl.Processor.importIntoDb(Processor.java:83)
	at nl.b3p.brmo.loader.util.TopNLRsgbTransformer.transform(TopNLRsgbTransformer.java:53)
	at nl.b3p.brmo.loader.util.TopNLRsgbTransformer.run(TopNLRsgbTransformer.java:89)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.sun.istack.SAXParseException2; lineNumber: 2484711; columnNumber: 3; unexpected element (uri:"http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.1", local:"FeatureMember"). Expected elements are <{http://www.opengis.net/gml/3.2}AbstractCurve>,<{http://www.opengis.net/gml/3.2}AbstractFeature>,<{http://www.opengis.net/gml/3.2}AbstractGML>,<{http://www.opengis.net/gml/3.2}AbstractGeometricAggregate>,<{http://www.opengis.net/gml/3.2}AbstractGeometricPrimitive>,<{http://www.opengis.net/gml/3.2}AbstractGeometry>,<{http://www.opengis.net/gml/3.2}AbstractMetaData>,<{http://www.opengis.net/gml/3.2}AbstractObject>,<{http://www.opengis.net/gml/3.2}AbstractSurface>,<{http://register.geostandaarden.nl/gmlapplicatieschema/brt-algemeen/1.2.0}BRTLijnOfPunt>,<{http://register.geostandaarden.nl/gmlapplicatieschema/brt-algemeen/1.2.0}BRTVlakLijnOfPunt>,<{http://register.geostandaarden.nl/gmlapplicatieschema/brt-algemeen/1.2.0}BRTVlakMultivlakOfPunt>,<{http://register.geostandaarden.nl/gmlapplicatieschema/brt-algemeen/1.2.0}BRTVlakOfLijn>,<{http://register.geostandaarden.nl/gmlapplicatieschema/brt-algemeen/1.2.0}BRTVlakOfMultivlak>,<{http://www.opengis.net/gml/3.2}Envelope>,<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}FeatureCollectionT250NL>,<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}FeatureMember>,<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}FunctioneelGebied>,<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}Gebouw>,<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}GeografischGebied>,<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}Hoogte>,<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}Inrichtingselement>,<{http://www.opengis.net/gml/3.2}LocationKeyWord>,<{http://www.opengis.net/gml/3.2}LocationString>,<{http://www.opengis.net/gml/3.2}MultiSurface>,<{http://register.geostandaarden.nl/gmlapplicatieschema/brt-algemeen/1.2.0}NEN3610ID>,<{http://www.opengis.net/gml/3.2}Null>,<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}Plaats>,<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}PlanTopografie>,<{http://www.opengis.net/gml/3.2}Point>,<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}RegistratiefGebied>,<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}Relief>,<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}Spoorbaandeel>,<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}Terrein>,<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}Waterdeel>,<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}Wegdeel>,<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}_Top250nlObject>,<{http://www.opengis.net/gml/3.2}boundedBy>,<{http://www.opengis.net/gml/3.2}coordinates>,<{http://www.opengis.net/gml/3.2}description>,<{http://www.opengis.net/gml/3.2}descriptionReference>,<{http://www.opengis.net/gml/3.2}identifier>,<{http://www.opengis.net/gml/3.2}location>,<{http://www.opengis.net/gml/3.2}metaDataProperty>,<{http://www.opengis.net/gml/3.2}name>,<{http://www.opengis.net/gml/3.2}pos>,<{http://www.opengis.net/gml/3.2}surfaceMember>,<{http://www.opengis.net/gml/3.2}surfaceMembers>
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext.handleEvent(UnmarshallingContext.java:741)
	at com.sun.xml.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:262)
	at com.sun.xml.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:257)
	at com.sun.xml.bind.v2.runtime.unmarshaller.Loader.reportUnexpectedChildElement(Loader.java:124)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext$DefaultRootLoader.childElement(UnmarshallingContext.java:1149)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:574)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:556)
	at com.sun.xml.bind.v2.runtime.unmarshaller.StAXStreamConnector.handleStartElement(StAXStreamConnector.java:246)
	at com.sun.xml.bind.v2.runtime.unmarshaller.StAXStreamConnector.bridge(StAXStreamConnector.java:180)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:415)
	... 5 more
Caused by: javax.xml.bind.UnmarshalException: unexpected element (uri:"http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.1", local:"FeatureMember"). Expected elements are <{http://www.opengis.net/gml/3.2}AbstractCurve>,<{http://www.opengis.net/gml/3.2}AbstractFeature>,<{http://www.opengis.net/gml/3.2}AbstractGML>,<{http://www.opengis.net/gml/3.2}AbstractGeometricAggregate>,<{http://www.opengis.net/gml/3.2}AbstractGeometricPrimitive>,<{http://www.opengis.net/gml/3.2}AbstractGeometry>,<{http://www.opengis.net/gml/3.2}AbstractMetaData>,<{http://www.opengis.net/gml/3.2}AbstractObject>,<{http://www.opengis.net/gml/3.2}AbstractSurface>,<{http://register.geostandaarden.nl/gmlapplicatieschema/brt-algemeen/1.2.0}BRTLijnOfPunt>,<{http://register.geostandaarden.nl/gmlapplicatieschema/brt-algemeen/1.2.0}BRTVlakLijnOfPunt>,<{http://register.geostandaarden.nl/gmlapplicatieschema/brt-algemeen/1.2.0}BRTVlakMultivlakOfPunt>,<{http://register.geostandaarden.nl/gmlapplicatieschema/brt-algemeen/1.2.0}BRTVlakOfLijn>,<{http://register.geostandaarden.nl/gmlapplicatieschema/brt-algemeen/1.2.0}BRTVlakOfMultivlak>,<{http://www.opengis.net/gml/3.2}Envelope>,<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}FeatureCollectionT250NL>,<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}FeatureMember>,<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}FunctioneelGebied>,<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}Gebouw>,<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}GeografischGebied>,<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}Hoogte>,<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}Inrichtingselement>,<{http://www.opengis.net/gml/3.2}LocationKeyWord>,<{http://www.opengis.net/gml/3.2}LocationString>,<{http://www.opengis.net/gml/3.2}MultiSurface>,<{http://register.geostandaarden.nl/gmlapplicatieschema/brt-algemeen/1.2.0}NEN3610ID>,<{http://www.opengis.net/gml/3.2}Null>,<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}Plaats>,<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}PlanTopografie>,<{http://www.opengis.net/gml/3.2}Point>,<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}RegistratiefGebied>,<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}Relief>,<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}Spoorbaandeel>,<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}Terrein>,<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}Waterdeel>,<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}Wegdeel>,<{http://register.geostandaarden.nl/gmlapplicatieschema/top250nl/1.2.0}_Top250nlObject>,<{http://www.opengis.net/gml/3.2}boundedBy>,<{http://www.opengis.net/gml/3.2}coordinates>,<{http://www.opengis.net/gml/3.2}description>,<{http://www.opengis.net/gml/3.2}descriptionReference>,<{http://www.opengis.net/gml/3.2}identifier>,<{http://www.opengis.net/gml/3.2}location>,<{http://www.opengis.net/gml/3.2}metaDataProperty>,<{http://www.opengis.net/gml/3.2}name>,<{http://www.opengis.net/gml/3.2}pos>,<{http://www.opengis.net/gml/3.2}surfaceMember>,<{http://www.opengis.net/gml/3.2}surfaceMembers>
	... 15 more


```

</details>

**Comment by mprins** [comment]
kennelijk heeft pdok het schema zonder melding vooraf of achteraf aangepast, vorige week ging dit nog goed...

**Comment by mprins** [comment]
de foutmeldingen worden ook nog ergens opgeslokt... de transformatie status zegt na afloop "RSGB_TOPNL_OK" ook niet goed...
