### ISSUE TITLE
`functionaristypering` bevat soms te lange waarde

### ISSUE THREAD

**Issue by mprins** [B3Partners/brmo#510]
### Probleem
Kolom `functionaristypering` van tabel `functionaris` heeft een breedte van 35 CHAR, daardoor past de waarde "Algemeen directeur / General Manager"  (36 CHAR) en niet in. Het is in eerste oogopslag niet duidelijk wat de max. waarde in het HR schema is.

### Versie
versie info: 1.6.0

### Server log
<details><summary>server log:</summary>

```

Controleer functionaris op primary key: [nhr.natPers.bsn.XXXXX, nhr.rechtspersoon.rsin.YYYY], rij bestaat: ja
Controleer herkomst_metadata op primary key: [functionaris, null, null], rij bestaat: nee
Update object (zonder vastlegging historie) in tabel: functionaris
SQL: update functionaris set fk_sc_lh_pes_sc_identif = ?, fk_sc_rh_pes_sc_identif = ?, bv_ovrg_volmacht = ?, bv_soort_handeling = ?, bev_met_andere_prsn = ?, functie = ?, functionaristypering = ?, indic_statutair_volmacht = ?, soort_bev = ?, volledig_beperkt_volmacht = ? where fk_sc_lh_pes_sc_identif = ?  and fk_sc_rh_pes_sc_identif = ? , params ([nhr.natPers.bsn.XXXXX, nhr.rechtspersoon.rsin.YYYY, Ja, magOpgaveHandelsregisterDoen, null, Gevolmachtigde, Algemeen directeur / General Manager, Nee, null, B, nhr.natPers.bsn.XXXXX, nhr.rechtspersoon.rsin.YYYY])
Aantal record updates: -1
Fout: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(35)
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2190)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:136)
	at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:97)
	at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:97)
	at nl.b3p.brmo.loader.RsgbProxy.createUpdateSql(RsgbProxy.java:1252)
	at nl.b3p.brmo.loader.RsgbProxy.parseNewData(RsgbProxy.java:769)
	at nl.b3p.brmo.loader.RsgbProxy.handle(RsgbProxy.java:538)
	at nl.b3p.brmo.loader.pipeline.ProcessDbXmlPipeline.work(ProcessDbXmlPipeline.java:17)
	at nl.b3p.brmo.loader.pipeline.BerichtPipelineThread.run(BerichtPipelineThread.java:87)



```

</details>

**Comment by mprins** [comment]
ook een mooie `Business Unit Director Electronic Security a.i.`
