### ISSUE TITLE
duplicaat commerciële vestigingen worden niet correct verwerkt

### ISSUE THREAD

**Issue by mprins** [B3Partners/brmo#512]
### Probleem
Als er via een bericht een commerciële vestiging is geladen en er via een ander bericht een duplicaat van die commerciële vestiging binnenkomt dan ontstaat daardoor een PK conflict.

Dit komt oa voor bij onderhavige, maar ook voor bijvoorbeeld VVE's die gevestigd zijn op het administratiekantoor dat het beheer uitvoert.

![image](https://user-images.githubusercontent.com/1165786/45611139-a1db5c00-ba5e-11e8-8848-84bbaaae871b.png)

### Versie
versie info: 1.6.0

### Server log
<details><summary>server log:</summary>

```

4-09-2018 15:07:10: transformeren nhr bericht object ref nhr.comVestg.000017926610, met id 32124663, berichtdatum 14-09-2018

Transformeren naar RSGB database-xml en lezen resultaat:  0,0s


14-09-2018 15:07:10:081: start verwerking nhr bericht object ref nhr.comVestg.000017926610, met id 32124663, berichtdatum 14-09-2018

Bericht was al getransformeerd in pipeline

 

Verwerk nieuw bericht

 

Controleer subject op primary key: [nhr.comVestg.000017926610], rij bestaat: nee

Normale toevoeging van object aan tabel: subject

SQL: insert into subject (identif, clazz, typering, naam, adres_binnenland, adres_buitenland, fk_15aoa_identif, emailadres, telefoonnummer, website_url) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?), params ([nhr.comVestg.000017926610, VESTIGING, VESTIGING, Air Products Holdings B.V., Boyneweg 10 3197LK Botlek Rotterdam, null, null, null, 0102961300, null])

Fout: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "subject_pk"

Detail: Key (identif)=(nhr.comVestg.000017926610) already exists.
            at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
            at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
            at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
            at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
            at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
            at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
            at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:120)
            at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:97)
            at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:97)
            at nl.b3p.brmo.loader.RsgbProxy.createInsertSql(RsgbProxy.java:1145)
            at nl.b3p.brmo.loader.RsgbProxy.parseNewData(RsgbProxy.java:726)
            at nl.b3p.brmo.loader.RsgbProxy.handle(RsgbProxy.java:538)
            at nl.b3p.brmo.loader.pipeline.ProcessDbXmlPipeline.work(ProcessDbXmlPipeline.java:17)
            at nl.b3p.brmo.loader.pipeline.BerichtPipelineThread.run(BerichtPipelineThread.java:87)
 

14-09-2018 15:07:10:097: einde verwerking, duur:  0,0s

```

</details>

**Comment by mprins** [comment]
Er zijn twee mogelijkheden: 
- de commerciële vestiging bijwerken met het laatst binnengekomen bericht
- het bericht als duplicaat markeren en verwerking negeren

Mogelijk zit de oorzaak in de wijze waarop datums gebruikt worden in staging tov. rsgb.

NB. niet onbelangrijk is dat het huidige mechanisme waarmee de data geladen wordt, uitsluit dat er inschrijvingen en dus ook vestigingen vervallen, er is namelijk geen was/wordt constructie in het koppelvlak, zie ook B3Partners/CVnHR-Open-Source#21

**Comment by mprins** [comment]
zie ook #522

**Comment by mprins** [comment]
De oorzaak hiervan zit in de CVnHR applicatie die per ingeschoten bericht middels een hack "STAGING_OK" berichten probeert te selecteren en de geselecteerde berichten probeert te transformeren; dit kan een race conditie opleveren

met verschillende berichten die in eerste instantie fout gingen tijdens laden via CVnHR niet kunnen reproduceren in de reguliere brmo workflow.
