### ISSUE TITLE
GDS2ophalen: java.lang.IllegalStateException: StAXSource

### ISSUE THREAD

**Issue by mprins** [B3Partners/brmo#53]
```
Afgiftes ophalen bij Kadaster afgifteservice (GDS2)

Gestart op: 2015-04-24 10:08:08, een paar seconden geleden. 
Update: 2015-04-24 10:08:21
Totaal: 3159
Verwerkt: 13
Status: Uitvoeren SOAP request naar Kadaster afgerond


Proces afgebroken vanwege een exception:
java.lang.IllegalStateException: StAXSource(XMLStreamReader) with XMLStreamReadernot in XMLStreamConstants.START_DOCUMENT or XMLStreamConstants.START_ELEMENT state
	at javax.xml.transform.stax.StAXSource.<init>(StAXSource.java:155)
	at nl.b3p.brmo.loader.xml.BrkSnapshotXMLReader.next(BrkSnapshotXMLReader.java:187)
	at nl.b3p.brmo.service.scanner.GDS2OphalenProces.laadAfgifte(GDS2OphalenProces.java:471)
	at nl.b3p.brmo.service.scanner.GDS2OphalenProces.verwerkAfgiftes(GDS2OphalenProces.java:596)
	at nl.b3p.brmo.service.scanner.GDS2OphalenProces.execute(GDS2OphalenProces.java:364)
	at nl.b3p.brmo.service.stripes.GDS2OphalenUitvoerActionBean.execute(GDS2OphalenUitvoerActionBean.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at net.sourceforge.stripes.controller.DispatcherHelper$6.intercept(DispatcherHelper.java:456)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:158)
	at net.sourceforge.stripes.controller.BeforeAfterMethodInterceptor.intercept(BeforeAfterMethodInterceptor.java:113)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at org.stripesstuff.plugin.waitpage.WaitPageInterceptor.intercept(WaitPageInterceptor.java:125)
	at net.sourceforge.stripes.controller.ExecutionContext.proceed(ExecutionContext.java:155)
	at net.sourceforge.stripes.controller.ExecutionContext.wrap(ExecutionContext.java:74)
	at net.sourceforge.stripes.controller.DispatcherHelper.invokeEventHandler(DispatcherHelper.java:454)
	at net.sourceforge.stripes.controller.DispatcherServlet.invokeEventHandler(DispatcherServlet.java:278)
	at net.sourceforge.stripes.controller.DispatcherServlet.service(DispatcherServlet.java:160)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at net.sourceforge.stripes.controller.StripesFilter.doFilter(StripesFilter.java:260)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:613)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1085)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1556)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1513)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Log:
Initialiseren... Fri Apr 24 10:08:08 CEST 2015
Kadaster endpoint: https://service30.kadaster.nl/gds2/afgifte/v20130701
Loading keystore
Initializing TrustManagerFactory
Initializing KeyManagerFactory
Initializing SSLContext

*** start periode ***
Aantal in antwoord: 2000
Meer afgiftes beschikbaar: true
Aantal in antwoord: 1159
Nog meer afgiftes beschikbaar: false
Downloaden https://service30.kadaster.nl/gds2/download/private/xxxxxxxxxxxxxx
Downloaden https://service30.kadaster.nl/gds2/download/private/xxxxxxxxxxxxxx
Downloaden https://service30.kadaster.nl/gds2/download/private/xxxxxxxxxxxxxx
Downloaden https://service30.kadaster.nl/gds2/download/private/xxxxxxxxxxxxxx
Downloaden https://service30.kadaster.nl/gds2/download/private/xxxxxxxxxxxxxx
Downloaden https://service30.kadaster.nl/gds2/download/private/xxxxxxxxxxxxxx
Downloaden https://service30.kadaster.nl/gds2/download/private/xxxxxxxxxxxxxx
Downloaden https://service30.kadaster.nl/gds2/download/private/xxxxxxxxxxxxxx
Downloaden https://service30.kadaster.nl/gds2/download/private/xxxxxxxxxxxxxx
Downloaden https://service30.kadaster.nl/gds2/download/private/xxxxxxxxxxxxxx
Downloaden https://service30.kadaster.nl/gds2/download/private/xxxxxxxxxxxxxx
Downloaden https://service30.kadaster.nl/gds2/download/private/xxxxxxxxxxxxxx
Downloaden https://service30.kadaster.nl/gds2/download/private/xxxxxxxxxxxxxx
Downloaden https://service30.kadaster.nl/gds2/download/private/xxxxxxxxxxxxxx
```

**Comment by onnlinetool** [comment]
Downloaden Downloaden Downloaden Downloaden Downloaden Downloaden Downloaden 

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi

Downloaden =========>>>>>>>>>> http://bit.ly/2oiWvqi
