### ISSUE TITLE
Transforming OPR causes error: ORA-12899: value too large for column

### ISSUE THREAD

**Issue by KJLammers** [B3Partners/brmo#538]
Was transforming OPR data of The Netherlands, transforming stopped because of this error:

```
2018-10-11 16:10:27 ERROR nl.b3p.brmo.loader.RsgbProxy#handle - Fout bij verwerking bericht met id 13990520, melding: ORA-12899: value too large for column "C##BRMO_RSGB"."GEM_OPENB_RMTE"."STRAATNAAM" (actual: 25, maximum: 24)

2018-10-11 16:10:27 DEBUG nl.b3p.brmo.loader.RsgbProxy#handle - Fout bij verwerking bericht met id 13990520
java.sql.SQLException: ORA-12899: value too large for column "C##BRMO_RSGB"."GEM_OPENB_RMTE"."STRAATNAAM" (actual: 25, maximum: 24)

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:494)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:446)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1054)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:623)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:252)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:612)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:226)
	at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:59)
	at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:910)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1119)
	at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3780)
	at oracle.jdbc.driver.T4CPreparedStatement.executeInternal(T4CPreparedStatement.java:1343)
	at oracle.jdbc.driver.OraclePreparedStatement.executeLargeUpdate(OraclePreparedStatement.java:3865)
	at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:3845)
	at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1061)
	at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:97)
	at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:97)
	at nl.b3p.brmo.loader.RsgbProxy.createInsertSql(RsgbProxy.java:1105)
	at nl.b3p.brmo.loader.RsgbProxy.parseNewData(RsgbProxy.java:722)
	at nl.b3p.brmo.loader.RsgbProxy.handle(RsgbProxy.java:538)
	at nl.b3p.brmo.loader.pipeline.ProcessDbXmlPipeline.work(ProcessDbXmlPipeline.java:17)
	at nl.b3p.brmo.loader.pipeline.BerichtPipelineThread.run(BerichtPipelineThread.java:87)
Caused by: Error : 12899, Position : 205, Sql = insert into gem_openb_rmte (DAT_BEG_GELDH, IDENTIFCODE, DATUM_EINDE_GELDH, INDIC_GECONST_OPENB_RMTE, NAAM_OPENB_RMTE, STATUS_OPENB_RMTE, STRAATNAAM, TYPE_OPENB_RMTE) values (:1 , :2 , :3 , :4 , :5 , :6 , :7 , :8 ), OriginalSql = insert into gem_openb_rmte (DAT_BEG_GELDH, IDENTIFCODE, DATUM_EINDE_GELDH, INDIC_GECONST_OPENB_RMTE, NAAM_OPENB_RMTE, STATUS_OPENB_RMTE, STRAATNAAM, TYPE_OPENB_RMTE) values (?, ?, ?, ?, ?, ?, ?, ?), Error Msg = ORA-12899: value too large for column "C##BRMO_RSGB"."GEM_OPENB_RMTE"."STRAATNAAM" (actual: 25, maximum: 24)

	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:498)
	... 21 more
2018-10-11 16:10:27 ERROR nl.b3p.brmo.loader.pipeline.ProcessDbXmlPipeline#run - work method threw exception (continuing): class java.lang.NullPointerException: null
2018-10-11 16:10:27 INFO  nl.b3p.brmo.loader.pipeline.ProcessDbXmlPipeline#run - aborting!
2018-10-11 16:10:27 ERROR nl.b3p.brmo.loader.RsgbProxy#run - Fout tijdens verwerken berichten

```

fix: Enlarge column STRAATNAAM in  table GEM_OPENB_RMTE

**Comment by KJLammers** [comment]
fixed it with:
ALTER table GEM_OPENB_RMTE modify STRAATNAAM VARCHAR2(100)

**Comment by mprins** [comment]
Het schema is niet correct aangemaakt; 
zoals op de wiki beschreven[1] moet de `NLS_LENGTH_SEMANTICS` op `CHAR` ingesteld staan, de default is `BYTE` en daardoor passen dingen niet als er een 2-byte character in een (verkorte) straatnaam zit.

[1] https://github.com/B3Partners/brmo/wiki/Installatiehandleiding#databaseserver-installatie-oracle

zie ook: #240
