### ISSUE TITLE
object_ref is null na parsen brk bericht

### ISSUE THREAD

**Issue by cvanlith** [B3Partners/brmo#64]
Object_ref is null na parsen BRK bericht maar de status staat wel op STAGING_OK. Dit moet minimaal STAGING_NOK zijn. Feitelijk is dit een serieuze fout die niet voor mag komen. 

2015-05-25 12:00:13 INFO  nl.b3p.brmo.service.scanner.GDS2OphalenProces#addLog - Downloaden https://service30.kadaster.nl/gds2/download/private/f92727c3-43ac-4f75-97fe-24dc5d9e93bf
2015-05-25 12:00:15 ERROR nl.b3p.brmo.loader.entity.BrkBericht#evaluateXPath - Error while getting brk referentie
java.lang.NullPointerException
	at nl.b3p.brmo.loader.entity.BrkBericht.evaluateXPath(BrkBericht.java:57)
	at nl.b3p.brmo.loader.entity.BrkBericht.getObjectRef(BrkBericht.java:84)
	at nl.b3p.brmo.service.scanner.GDS2OphalenProces.laadAfgifte(GDS2OphalenProces.java:495)
	at nl.b3p.brmo.service.scanner.GDS2OphalenProces.verwerkAfgiftes(GDS2OphalenProces.java:620)
	at nl.b3p.brmo.service.scanner.GDS2OphalenProces.execute(GDS2OphalenProces.java:377)
	at nl.b3p.brmo.service.stripes.GDS2OphalenUitvoerActionBean.execute(GDS2OphalenUitvoerActionBean.java:118)

**Comment by matthijsln** [comment]
De NullPointerException was wel op een gekke plek in BrkBericht, zou erop duiden dat de XPathExpression null was. Dit zou niet voor moeten komen (is niet afhankelijk van het specifieke bericht). Origineel bericht ook niet kunnen vinden om te testen, maar voor toekomstige berichten wordt bij een exception uit BrkBericht de status op STAGING_NOK gezet en de exception stacktrace in de opmerking gezet.
