### ISSUE TITLE
fout bij laden via BRKDirectoryScanner

### ISSUE THREAD

**Issue by mprins** [B3Partners/brmo#67]
```
2015-06-16 17:27:00 INFO  nl.b3p.brmo.service.scanner.BRKDirectoryScanner#execute - De BRK scanner met ID 2 is gestart op Tue Jun 16 17:27:00 CEST 2015.
2015-06-16 17:27:00 INFO  nl.b3p.brmo.service.scanner.BRKDirectoryScanner#execute - Bestand /data/BRK_Downloads/brk/post-op-2015-06-16-17_01_54_239.xml is gevonden in /data/BRK_Downloads/brk.
2015-06-16 17:27:00 INFO  nl.b3p.brmo.service.scanner.BRKDirectoryScanner#execute - Bestand /data/BRK_Downloads/brk/post-op-2015-06-16-17_01_54_239.xml is naar archief /data/BRK_Downloads/brk/archief verplaatst.
2015-06-16 17:27:00 ERROR nl.b3p.brmo.service.jobs.AutomatischProcesJob#execute - Fout tijdens starten of uitvoeren van automatische proces met id: 2
nl.b3p.brmo.loader.util.BrmoException: Fout bij loaden basisregistratie gegevens
	at nl.b3p.brmo.loader.BrmoFramework.loadFromFile(BrmoFramework.java:156)
	at nl.b3p.brmo.service.scanner.BRKDirectoryScanner.execute(BRKDirectoryScanner.java:105)
	at nl.b3p.brmo.service.jobs.AutomatischProcesJob.execute(AutomatischProcesJob.java:37)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: nl.b3p.brmo.loader.util.BrmoException: Fout bij loaden basisregistratie gegevens
	at nl.b3p.brmo.loader.BrmoFramework.loadFromFile(BrmoFramework.java:215)
	at nl.b3p.brmo.loader.BrmoFramework.loadFromFile(BrmoFramework.java:154)
	... 4 more
Caused by: nl.b3p.brmo.loader.util.BrmoException: Header van bestand bevat geen datum, verkeerd formaat?
	at nl.b3p.brmo.loader.StagingProxy.loadBr(StagingProxy.java:496)
	at nl.b3p.brmo.loader.BrmoFramework.loadFromFile(BrmoFramework.java:209)
	... 5 more
```

vermoedelijk al opgelost in de JPA versie, maar de BRKDirectoryScanner gebruikt nog de StagingProxy (zonder JPA)

**Comment by mprins** [comment]
vanaf versie 1.2.5 gebruikt BRKDirectoryScanner JPA, deze specifieke fout zal dus niet meer optreden omdat het parsen en de foutafhandeling anders is is gewroden.
