### ISSUE TITLE
TOP250NL unit tests mislukken

### ISSUE THREAD

**Issue by mprins** [B3Partners/brmo#675]
### Probleem
De TOP250NL unit tests mislukken op dit moment, mogelijk heeft Kadaster/pdok het GML schema weer eens aangepast of de namen van de downloads.

### Versie
versie info: master

### Server log
<details><summary>server log:</summary>

```

18:49:36  BRMO-LOADER-TEST:  INFO 18:49:36 (n.b.TopNLParserIntegrationTest#startTest:82) - ==== Start test methode: testParse[argumenten rij 3: type: TOP250NL, bestand: /topnl/TOP250NL.gml]
18:49:36  BRMO-LOADER-TEST: ERROR 18:49:36 (n.b.t.Processor#parse:139) - Cannot retrieve topnltype: 
18:49:36  org.jdom2.input.JDOMParseException: Error on line 1 of document file:/var/lib/jenkins/workspace/BRMO_master/brmo-loader/target/test-classes/topnl/TOP250NL.gml: Premature end of file.
18:49:36  	at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:228)
18:49:36  	at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:277)
18:49:36  	at org.jdom2.input.SAXBuilder.build(SAXBuilder.java:1141)
18:49:36  	at nl.b3p.topnl.TopNLTypeFactory.getTopNLType(TopNLTypeFactory.java:38)
18:49:36  	at nl.b3p.topnl.Processor.parse(Processor.java:116)
18:49:36  	at nl.b3p.TopNLParserIntegrationTest.testParse(TopNLParserIntegrationTest.java:110)
18:49:36  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18:49:36  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
18:49:36  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:49:36  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
18:49:36  	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
18:49:36  	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
18:49:36  	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
18:49:36  	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
18:49:36  	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
18:49:36  	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
18:49:36  	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
18:49:36  	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
18:49:36  	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
18:49:36  	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
18:49:36  	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
18:49:36  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
18:49:36  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
18:49:36  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
18:49:36  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
18:49:36  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
18:49:36  	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
18:49:36  	at org.junit.runners.Suite.runChild(Suite.java:128)
18:49:36  	at org.junit.runners.Suite.runChild(Suite.java:27)
18:49:36  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
18:49:36  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
18:49:36  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
18:49:36  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
18:49:36  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
18:49:36  	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
18:49:36  	at org.junit.runners.Suite.runChild(Suite.java:128)
18:49:36  	at org.junit.runners.Suite.runChild(Suite.java:27)
18:49:36  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
18:49:36  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
18:49:36  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
18:49:36  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
18:49:36  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
18:49:36  	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
18:49:36  	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
18:49:36  	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
18:49:36  	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
18:49:36  	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
18:49:36  	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
18:49:36  	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
18:49:36  	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
18:49:36  	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
18:49:36  	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
18:49:36  	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
18:49:36  Caused by: org.xml.sax.SAXParseException; systemId: file:/var/lib/jenkins/workspace/BRMO_master/brmo-loader/target/test-classes/topnl/TOP250NL.gml; lineNumber: 1; columnNumber: 1; Premature end of file.
18:49:36  	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
18:49:36  	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:178)
18:49:36  	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
18:49:36  	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
18:49:36  	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1471)
18:49:36  	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:1013)
18:49:36  	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
18:49:36  	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
18:49:36  	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
18:49:36  	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
18:49:36  	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
18:49:36  	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
18:49:36  	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
18:49:36  	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
18:49:36  	at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:217)
18:49:36  	... 52 more
18:49:36  BRMO-LOADER-TEST:  INFO 18:49:36 (n.b.TopNLParserIntegrationTest#endTest:90) - ==== Einde test methode: testParse[argumenten rij 3: type: TOP250NL, bestand: /topnl/TOP250NL.gml]
18:49:36  [ERROR] Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.253 s <<< FAILURE! - in nl.b3p.TopNLParserIntegrationTest
18:49:36  [ERROR] testParse[argumenten rij 3: type: TOP250NL, bestand: /topnl/TOP250NL.gml](nl.b3p.TopNLParserIntegrationTest)  Time elapsed: 0.21 s  <<< FAILURE!
18:49:36  java.lang.AssertionError: Er moet meer dan 1 element in de parse lijst zitten
18:49:36  	at org.junit.Assert.fail(Assert.java:88)
18:49:36  	at org.junit.Assert.assertTrue(Assert.java:41)
18:49:36  	at nl.b3p.TopNLParserIntegrationTest.testParse(TopNLParserIntegrationTest.java:112)
18:49:36  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
18:49:36  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
18:49:36  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
18:49:36  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
18:49:36  	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
18:49:36  	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
18:49:36  	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
18:49:36  	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
18:49:36  	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
18:49:36  	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
18:49:36  	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
18:49:36  	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
18:49:36  	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
18:49:36  	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
18:49:36  	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
18:49:36  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
18:49:36  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
18:49:36  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
18:49:36  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
18:49:36  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
18:49:36  	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
18:49:36  	at org.junit.runners.Suite.runChild(Suite.java:128)
18:49:36  	at org.junit.runners.Suite.runChild(Suite.java:27)
18:49:36  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
18:49:36  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
18:49:36  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
18:49:36  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
18:49:36  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
18:49:36  	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
18:49:36  	at org.junit.runners.Suite.runChild(Suite.java:128)
18:49:36  	at org.junit.runners.Suite.runChild(Suite.java:27)
18:49:36  	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
18:49:36  	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
18:49:36  	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
18:49:36  	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
18:49:36  	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
18:49:36  	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
18:49:36  	at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
18:49:36  	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
18:49:36  	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
18:49:36  	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
18:49:36  	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
18:49:36  	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
18:49:36  	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
18:49:36  	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
18:49:36  	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
18:49:36  	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

```

</details>

**Comment by mprins** [comment]
zie ook #394 en #395
