### ISSUE TITLE
BRKDirectoryScanner crashed als bestand null karakters (\u0000) bevat

### ISSUE THREAD

**Issue by mprins** [B3Partners/brmo#75]
In geldige bestanden komt dit niet voor maar via de esb van SKP is een bestand binnengekomen dat een lange rij null karakters (\u0000 of 0x00) bevat. 

Op het moment dat het bestand naar string is geparsed en in het Bericht is gestopt en hibernate de insert commit treedt er een fout op omdat er een invalid byte sequence in het bericht zit

```
2015-07-01 11:02:00 WARN  org.hibernate.util.JDBCExceptionReporter#logExceptions - SQL Error: 0, SQLState: 22021
2015-07-01 11:02:00 ERROR org.hibernate.util.JDBCExceptionReporter#logExceptions - ERROR: invalid byte sequence for encoding "UTF8": 0x00
2015-07-01 11:02:00 ERROR org.quartz.core.JobRunShell#run - Job DEFAULT.proces_4 threw an unhandled Exception: 
javax.persistence.RollbackException: Transaction marked as rollbackOnly
	at org.hibernate.ejb.TransactionImpl.commit(TransactionImpl.java:73)
	at nl.b3p.brmo.service.jobs.AutomatischProcesJob.execute(AutomatischProcesJob.java:62)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
2015-07-01 11:02:00 ERROR org.quartz.core.ErrorLogger#schedulerError - Job (DEFAULT.proces_4 threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: javax.persistence.RollbackException: Transaction marked as rollbackOnly]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: javax.persistence.RollbackException: Transaction marked as rollbackOnly
	at org.hibernate.ejb.TransactionImpl.commit(TransactionImpl.java:73)
	at nl.b3p.brmo.service.jobs.AutomatischProcesJob.execute(AutomatischProcesJob.java:62)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	... 1 more
```

op te lossen door:
```java
                    // null karakters verwijderen uit het bestand
                    String fileContent = FileUtils.readFileToString(f, "UTF-8");
                    fileContent = fileContent.replaceAll("\u0000.*", "");
                    b.setBr_orgineel_xml(fileContent);
``` 
ipv.
```
                    b.setBr_orgineel_xml(FileUtils.readFileToString(f, "UTF-8"));
```

In potentie zou dit een DOS op kunnen leveren, ondanks dat het koppelvlak vertrouwd is.

**Comment by mprins** [comment]
quick fix in 0c68b09592d26181f5f41f922c230e7ae1180c5d door de ongeldige karakters eruit te filteren
