### ISSUE TITLE
ArrayIndexOutOfBoundsException tijdens transformeren (oracle driver 12.1.0.1)

### ISSUE THREAD

**Issue by mprins** [B3Partners/brmo#89]
Als ik probeer een record te transformeren naar RSGB krijg ik de volgende error in beeld:

 
```
java.lang.ArrayIndexOutOfBoundsException: -1
                at oracle.jdbc.driver.OracleParameterMetaDataParser.computeBasicInfo(OracleParameterMetaDataParser.java:199)
                at oracle.jdbc.driver.OracleParameterMetaDataParser.getParameterMetaDataSql(OracleParameterMetaDataParser.java:432)
                at oracle.jdbc.driver.OracleParameterMetaData.getParameterMetaData(OracleParameterMetaData.java:58)
                at oracle.jdbc.driver.OraclePreparedStatement.getParameterMetaData(OraclePreparedStatement.java:11621)
                at oracle.jdbc.driver.OraclePreparedStatementWrapper.getParameterMetaData(OraclePreparedStatementWrapper.java:1552)
                at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.getParameterMetaData(DelegatingPreparedStatement.java:265)
                at org.apache.tomcat.dbcp.dbcp2.DelegatingPreparedStatement.getParameterMetaData(DelegatingPreparedStatement.java:265)
                at org.apache.commons.dbutils.AbstractQueryRunner.fillStatement(AbstractQueryRunner.java:225)
                at org.apache.commons.dbutils.QueryRunner.query(QueryRunner.java:346)
                at org.apache.commons.dbutils.QueryRunner.query(QueryRunner.java:212)
                at nl.b3p.brmo.loader.StagingProxy.handleBerichtenByJob(StagingProxy.java:248)
                at nl.b3p.brmo.loader.RsgbProxy.run(RsgbProxy.java:245)
                at java.lang.Thread.run(Unknown Source)
```

**Comment by mprins** [comment]
lijkt een driver probleem te zijn; 
de volgende testcase gemaakt om dat te toetsen:
```java

import java.sql.*;

class OracleTest {

    public static void main(String[] args) throws Exception {
        Class.forName("oracle.jdbc.OracleDriver");

        if (args.length != 3) {
            System.out.println("args: url user pass");
            System.out.println("url: jdbc:oracle:thin:@//<host>:1521/<sid>");
            System.exit(1);
        }

        Connection conn = DriverManager.getConnection(args[0], args[1], args[2]);

        try {
            String prepSQL = "select * from (select /*+ FIRST_ROWS(n) */ a.*, ROWNUM rnum from (select * from bericht where job_id = ? order by soort, object_ref, datum, volgordenummer ) a where ROWNUM <=250 ) where rnum  > 0";
            try {
                PreparedStatement pstmt = conn.prepareStatement(prepSQL);
                int stmtCount = pstmt.getParameterMetaData().getParameterCount();
                System.out.println("Poging met getParameterMetaData, stmtCount=" + stmtCount);
                pstmt.setLong(1, 1444897737715L);
                ResultSet prset = pstmt.executeQuery();
                while (prset.next()) {
                    System.out.println(prset.getString(1));
                }
            } catch (Exception e) {
                System.err.println(e);
            }
            try {
                PreparedStatement pstmt = conn.prepareStatement(prepSQL);
                System.out.println("Poging zonder getParameterMetaData");
                pstmt.setLong(1, 1444897737715L);
                ResultSet prset = pstmt.executeQuery();
                while (prset.next()) {
                    System.out.println(prset.getString(1));
                }
            } catch (Exception e) {
                System.err.println(e);
            }
        } finally {
            try {
                conn.close();
            } catch (Exception ignore) {
                // ignore error closing db
            }
        }
    }
}
```
eg. 
```
javac -cp /home/mark/.m2/repository/com/oracle/ojdbc5/11.1.0.7.0/ojdbc5-11.1.0.7.0.jar OracleTest.java
java -cp /home/mark/.m2/repository/com/oracle/ojdbc5/11.1.0.7.0/ojdbc5-11.1.0.7.0.jar OracleTest jdbc:oracle:thin:@b3p-demoserver:1521:orcl <user> <pass> 

```

**Comment by mprins** [comment]
output met ojdbc7.jar

```
java.lang.ArrayIndexOutOfBoundsException: -1
Poging zonder getParameterMetaData

```

**Comment by mprins** [comment]
Ik heb onze testcase met een serie verschillende drivers geprobeerd (tegen onze 11g database), resultaat:


java -cp ./ojdbc5-11.1.0.7.jar:. OracleTest jdbc:oracle:thin:@b3p-demoserver:1521:orcl *** ***
OK

java -cp ./ojdbc6-11.2.0.4.jar:. OracleTest jdbc:oracle:thin:@b3p-demoserver:1521:orcl *** ***
OK

java -cp ./ojdbc6-12.1.0.2.jar:. OracleTest jdbc:oracle:thin:@b3p-demoserver:1521:orcl *** ***
OK

java -cp ./ojdbc7-12.1.0.2.jar:. OracleTest jdbc:oracle:thin:@b3p-demoserver:1521:orcl *** ***
OK

java -cp ./ojdbc5-11.2.0.4.jar:. OracleTest jdbc:oracle:thin:@b3p-demoserver:1521:orcl *** ***
OK

java -cp ./ojdbc6-12.1.0.1.jar:. OracleTest jdbc:oracle:thin:@b3p-demoserver:1521:orcl *** ***
NOT OK

java -cp ./ojdbc7-12.1.0.1.jar:. OracleTest jdbc:oracle:thin:@b3p-demoserver:1521:orcl *** ***
NOT OK

Het lijkt erop dat het euvel in de 12.1.0.2 versie van de driver is opgelost.

**Comment by mprins** [comment]
Opgelost met een nieuwe oracle (ojdbc7) driver

**Comment by mprins** [comment]
wiki: https://github.com/B3Partners/brmo/wiki/welke-jdbc-diver%3F
