### ISSUE TITLE
UnsupportedOperationException bij insert KAD_PERCEEL

### ISSUE THREAD

**Issue by mprins** [B3Partners/brmo#94]
```log
Controleer kad_perceel op primary key: [53550018870000], rij bestaat: nee

Normale toevoeging van object aan tabel: kad_perceel

Fout: java.lang.UnsupportedOperationException: Data type SDO_GEOMETRY (#2002) of column "begrenzing_perceel" not supported

        at nl.b3p.brmo.loader.RsgbProxy.createInsertSql(RsgbProxy.java:933)

        at nl.b3p.brmo.loader.RsgbProxy.parseNewData(RsgbProxy.java:598)

        at nl.b3p.brmo.loader.RsgbProxy.handle(RsgbProxy.java:450)

        at nl.b3p.brmo.loader.pipeline.ProcessDbXmlPipeline.work(ProcessDbXmlPipeline.java:17)

        at nl.b3p.brmo.loader.pipeline.BerichtPipelineThread.run(BerichtPipelineThread.java:83)

1444984002,4s
```

**Comment by mprins** [comment]
er zijn er meer,

```
2015-10-19 16:49:40 ERROR nl.b3p.brmo.loader.RsgbProxy#handle - Fout bij verwerking bericht met id 224
java.lang.UnsupportedOperationException: Data type SDO_GEOMETRY (#2002) of column "begrenzing_perceel" not supported
	at nl.b3p.brmo.loader.RsgbProxy.createUpdateSql(RsgbProxy.java:1109)
	at nl.b3p.brmo.loader.RsgbProxy.parseNewData(RsgbProxy.java:654)
	at nl.b3p.brmo.loader.RsgbProxy.handle(RsgbProxy.java:452)
	at nl.b3p.brmo.loader.pipeline.ProcessDbXmlPipeline.work(ProcessDbXmlPipeline.java:17)
	at nl.b3p.brmo.loader.pipeline.BerichtPipelineThread.run(BerichtPipelineThread.java:83)
```
